name: Build Sphinx Documentation

on:
  push:
    branches:
      - main  # Adjust this to your main branch
  pull_request:
    branches:
      - main  # Optionally build on PRs to the main branch

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        # Add other Sphinx dependencies here

    - name: Build the documentation
      run: |
        cd docs
        make html

    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: sphinx-docs
        path: docs/build/html

